
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ActStatus
    {
        IdleOrWalk = 0,
        Run = 1,
        SkillUpParry = 2,
        SkillLeftParry = 3,
        SkillRightParry = 4,
        SkillDownParry = 5,
        SkillOtherParry = 6,
        Skill1Act = 7,
        Skill2Act = 8,
        Skill3Act = 9,
        Skill4Act = 10,
        Skill5Act = 11,
        OnDash = 12,
        OnCatchOrBlock = 13,
        Max = 14,
    }

} 

