
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ActStatus
    {
        Undefine = 0,
        IdleOrWalk = 1,
        Run = 2,
        SkillUpParry = 3,
        SkillLeftParry = 4,
        SkillRightParry = 5,
        SkillDownParry = 6,
        SkillOtherParry = 7,
        Skill1Act = 8,
        Skill2Act = 9,
        Skill3Act = 10,
        Skill4Act = 11,
        Skill5Act = 12,
        OnDash = 13,
        OnCatchOrBlock = 14,
    }

} 

