
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ActStatus
    {
        Undefine = 0,
        IdleOrWalk = 1,
        Run = 2,
        Skill1Parry = 3,
        Skill2Parry = 4,
        Skill3Parry = 5,
        Skill4Parry = 6,
        Skill5Parry = 7,
        Skill1Act = 8,
        Skill2Act = 9,
        Skill3Act = 10,
        Skill4Act = 11,
        Skill5Act = 12,
        Skill1Dodge = 13,
        Skill2Dodge = 14,
        Skill3Dodge = 15,
        Skill4Dodge = 16,
        Skill5Dodge = 17,
        OnDash = 18,
        OnBadParry = 19,
        OnCatchAtk = 20,
    }

} 

