
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AtkDirType
    {
        Up = 0,
        Left = 1,
        Right = 2,
        Down = 3,
        Other = 4,
    }

} 

