
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum AtkDirType
    {
        Up = 1,
        Left = 2,
        Right = 4,
        Down = 8,
        Other = 16,
        Any = Up|Left|Right|Down|Other,
    }

} 

