
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum BodyStatus
    {
        Active = 1,
        Break = 2,
        Dead = 4,
        Alive = Active|Break,
        Any = Active|Break|Dead,
    }

} 

