
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ColliderShape
    {
        None = 0,
        Sphere = 1,
        Box = 2,
        Sector = 3,
        SphereCast = 4,
    }

} 

