
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EffectType
    {
        Undefine = 0,
        StandardDamage = 1,
        Push = 2,
        Pull = 3,
        Caught = 4,
        Lock = 5,
    }

} 

