
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LauncherCfg : Luban.BeanBase
{
    public LauncherCfg(ByteBuf _buf) 
    {
        LaunchTime = _buf.ReadInt();
        OffSetXInt = _buf.ReadInt();
        OffSetZInt = _buf.ReadInt();
        RotateY = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MediaAlias = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); MediaAlias[__index0] = __e0;}}
    }

    public static LauncherCfg DeserializeLauncherCfg(ByteBuf _buf)
    {
        return new LauncherCfg(_buf);
    }

    public readonly int LaunchTime;
    public readonly int OffSetXInt;
    public readonly int OffSetZInt;
    public readonly int RotateY;
    public readonly string[] MediaAlias;
   
    public const int __ID__ = 1443232900;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "launchTime:" + LaunchTime + ","
        + "offSetXInt:" + OffSetXInt + ","
        + "offSetZInt:" + OffSetZInt + ","
        + "rotateY:" + RotateY + ","
        + "mediaAlias:" + Luban.StringUtil.CollectionToString(MediaAlias) + ","
        + "}";
    }
}

}

