
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum MediaType
    {
        Undefine = 0,
        Self = 1,
        Link = 2,
        Melee = 3,
        Range = 4,
        Lock = 5,
    }

} 

