
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class MovementChangeCfg : Luban.BeanBase
{
    public MovementChangeCfg(ByteBuf _buf) 
    {
        ChangeTime = _buf.ReadInt();
        ZInt = _buf.ReadInt();
        XInt = _buf.ReadInt();
    }

    public static MovementChangeCfg DeserializeMovementChangeCfg(ByteBuf _buf)
    {
        return new MovementChangeCfg(_buf);
    }

    public readonly int ChangeTime;
    public readonly int ZInt;
    public readonly int XInt;
   
    public const int __ID__ = -1449801083;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "changeTime:" + ChangeTime + ","
        + "zInt:" + ZInt + ","
        + "xInt:" + XInt + ","
        + "}";
    }
}

}

