
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum OpAct
    {
        Undefine = 0,
        OpAct1 = 1,
        OpAct2 = 2,
        OpAct3 = 3,
        OpAct4 = 4,
        Release = 5,
    }

} 

