
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillParryCfg : Luban.BeanBase
{
    public SkillParryCfg(ByteBuf _buf) 
    {
        ParryBuffAliasToBeCaught = _buf.ReadString();
        SkillLaunchCfg = global::cfg.SkillLaunchCfg.DeserializeSkillLaunchCfg(_buf);
    }

    public static SkillParryCfg DeserializeSkillParryCfg(ByteBuf _buf)
    {
        return new SkillParryCfg(_buf);
    }

    /// <summary>
    /// 被抓Buff别名
    /// </summary>
    public readonly string ParryBuffAliasToBeCaught;
    /// <summary>
    /// 技能Act
    /// </summary>
    public readonly SkillLaunchCfg SkillLaunchCfg;
   
    public const int __ID__ = -2080077331;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SkillLaunchCfg?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "parryBuffAliasToBeCaught:" + ParryBuffAliasToBeCaught + ","
        + "skillLaunchCfg:" + SkillLaunchCfg + ","
        + "}";
    }
}

}

