
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillLaunchCfg : Luban.BeanBase
{
    public SkillLaunchCfg(ByteBuf _buf) 
    {
        SkillActAlias = _buf.ReadString();
        NextComboStatus = (ActStatus)_buf.ReadInt();
    }

    public static SkillLaunchCfg DeserializeSkillLaunchCfg(ByteBuf _buf)
    {
        return new SkillLaunchCfg(_buf);
    }

    public readonly string SkillActAlias;
    public readonly ActStatus NextComboStatus;
   
    public const int __ID__ = 1110741120;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "skillActAlias:" + SkillActAlias + ","
        + "nextComboStatus:" + NextComboStatus + ","
        + "}";
    }
}

}

