
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public battle.TbSkillActCfg TbSkillActCfg {get; }
    public battle.TbEffectCfg TbEffectCfg {get; }
    public battle.TbBodyCfg TbBodyCfg {get; }
    public battle.TbCommonCfg TbCommonCfg {get; }
    public battle.TbMediaCfg TbMediaCfg {get; }
    public battle.TbWeaponTypeCfg TbWeaponTypeCfg {get; }
    public Tbtest Tbtest {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbSkillActCfg = new battle.TbSkillActCfg(loader("battle_tbskillactcfg"));
        TbEffectCfg = new battle.TbEffectCfg(loader("battle_tbeffectcfg"));
        TbBodyCfg = new battle.TbBodyCfg(loader("battle_tbbodycfg"));
        TbCommonCfg = new battle.TbCommonCfg(loader("battle_tbcommoncfg"));
        TbMediaCfg = new battle.TbMediaCfg(loader("battle_tbmediacfg"));
        TbWeaponTypeCfg = new battle.TbWeaponTypeCfg(loader("battle_tbweapontypecfg"));
        Tbtest = new Tbtest(loader("tbtest"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbSkillActCfg.ResolveRef(this);
        TbEffectCfg.ResolveRef(this);
        TbBodyCfg.ResolveRef(this);
        TbCommonCfg.ResolveRef(this);
        TbMediaCfg.ResolveRef(this);
        TbWeaponTypeCfg.ResolveRef(this);
        Tbtest.ResolveRef(this);
    }
}

}
