
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum TargetTypeTag
    {
        Self = 1,
        OtherAlly = 2,
        Enemy = 4,
        AllOther = OtherAlly|Enemy,
        Allies = Self|OtherAlly,
    }

} 

