
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum TargetTraceMode
    {
        None = 0,
        Normal = 1,
        Break = 2,
        BuffMark = 3,
        Self = 4,
    }

} 

