
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Tbtest
{
    private readonly System.Collections.Generic.Dictionary<int, test> _dataMap;
    private readonly System.Collections.Generic.List<test> _dataList;
    
    public Tbtest(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, test>();
        _dataList = new System.Collections.Generic.List<test>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            test _v;
            _v = global::cfg.test.Deserializetest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, test> DataMap => _dataMap;
    public System.Collections.Generic.List<test> DataList => _dataList;

    public test GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public test Get(int key) => _dataMap[key];
    public test this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

