
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class BodyCfg : Luban.BeanBase
{
    public BodyCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Alias = _buf.ReadString();
        ResPath = _buf.ReadString();
        WeightParam = _buf.ReadInt();
        Name = _buf.ReadString();
        MaxHp = _buf.ReadInt();
        LessHpRate = _buf.ReadInt();
        MaxGp = _buf.ReadInt();
        LessGpRate = _buf.ReadInt();
        GpRegPerSec = _buf.ReadInt();
        GpRegDelayTime = _buf.ReadInt();
        MaxSp = _buf.ReadInt();
        LessSpRate = _buf.ReadInt();
        SpRegPerSec = _buf.ReadInt();
        SpRegDelayTime = _buf.ReadInt();
        BaseAtk = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
    }

    public static BodyCfg DeserializeBodyCfg(ByteBuf _buf)
    {
        return new battle.BodyCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly string Alias;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// 质量参数
    /// </summary>
    public readonly int WeightParam;
    public readonly string Name;
    /// <summary>
    /// Hp最大值
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// Hp缺乏刻度万份比
    /// </summary>
    public readonly int LessHpRate;
    /// <summary>
    /// Gp最大值
    /// </summary>
    public readonly int MaxGp;
    /// <summary>
    /// Gp缺乏刻度万份比
    /// </summary>
    public readonly int LessGpRate;
    public readonly int GpRegPerSec;
    public readonly int GpRegDelayTime;
    /// <summary>
    /// Sp最大值
    /// </summary>
    public readonly int MaxSp;
    /// <summary>
    /// Sp缺乏刻度万份比
    /// </summary>
    public readonly int LessSpRate;
    public readonly int SpRegPerSec;
    public readonly int SpRegDelayTime;
    /// <summary>
    /// 基础攻击
    /// </summary>
    public readonly int BaseAtk;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int MoveSpeed;
   
    public const int __ID__ = 1771869196;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "alias:" + Alias + ","
        + "resPath:" + ResPath + ","
        + "weightParam:" + WeightParam + ","
        + "name:" + Name + ","
        + "MaxHp:" + MaxHp + ","
        + "LessHpRate:" + LessHpRate + ","
        + "MaxGp:" + MaxGp + ","
        + "LessGpRate:" + LessGpRate + ","
        + "GpRegPerSec:" + GpRegPerSec + ","
        + "GpRegDelayTime:" + GpRegDelayTime + ","
        + "MaxSp:" + MaxSp + ","
        + "LessSpRate:" + LessSpRate + ","
        + "SpRegPerSec:" + SpRegPerSec + ","
        + "SpRegDelayTime:" + SpRegDelayTime + ","
        + "BaseAtk:" + BaseAtk + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "}";
    }
}

}

