
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class CommonCfg : Luban.BeanBase
{
    public CommonCfg(ByteBuf _buf) 
    {
        TickTime = _buf.ReadInt();
        TickToughGrow = _buf.ReadInt();
        MinActTime = _buf.ReadInt();
        MaxActTime = _buf.ReadInt();
        AvgActTime = _buf.ReadInt();
        Friction = _buf.ReadInt();
        DrawStunAlias = _buf.ReadString();
    }

    public static CommonCfg DeserializeCommonCfg(ByteBuf _buf)
    {
        return new battle.CommonCfg(_buf);
    }

    /// <summary>
    /// 每个tick的时间
    /// </summary>
    public readonly int TickTime;
    public readonly int TickToughGrow;
    /// <summary>
    /// 最小动作判定时间0,小于等于此值的动作不在博弈空间内
    /// </summary>
    public readonly int MinActTime;
    /// <summary>
    /// 最大动作判定时间20
    /// </summary>
    public readonly int MaxActTime;
    /// <summary>
    /// 均值
    /// </summary>
    public readonly int AvgActTime;
    /// <summary>
    /// 摩擦加速度值 mm*s^-2
    /// </summary>
    public readonly int Friction;
    /// <summary>
    /// 判定平局触发的效果
    /// </summary>
    public readonly string DrawStunAlias;
   
    public const int __ID__ = -753315677;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tickTime:" + TickTime + ","
        + "TickToughGrow:" + TickToughGrow + ","
        + "minActTime:" + MinActTime + ","
        + "maxActTime:" + MaxActTime + ","
        + "avgActTime:" + AvgActTime + ","
        + "friction:" + Friction + ","
        + "DrawStunAlias:" + DrawStunAlias + ","
        + "}";
    }
}

}

