
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class MediaCfg : Luban.BeanBase
{
    public MediaCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Alias = _buf.ReadString();
        ViewResPath = _buf.ReadString();
        ColliderShapeType = (ColliderShape)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ColliderParam = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ColliderParam.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Movement = new System.Collections.Generic.List<MovementChangeCfg>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MovementChangeCfg _e0;  _e0 = global::cfg.MovementChangeCfg.DeserializeMovementChangeCfg(_buf); Movement.Add(_e0);}}
        Duration = _buf.ReadInt();
        HitMaxCount = _buf.ReadInt();
        HitGapTime = _buf.ReadInt();
        CustemToughPower = _buf.ReadInt();
        MediaType = (MediaType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MediaExtraParameters = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); MediaExtraParameters.Add(_e0);}}
        TargetType = (TargetTypeTag)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EffectAlias = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); EffectAlias.Add(_e0);}}
    }

    public static MediaCfg DeserializeMediaCfg(ByteBuf _buf)
    {
        return new battle.MediaCfg(_buf);
    }

    public readonly int Id;
    public readonly string Alias;
    public readonly string ViewResPath;
    public readonly ColliderShape ColliderShapeType;
    public readonly System.Collections.Generic.List<int> ColliderParam;
    public readonly System.Collections.Generic.List<MovementChangeCfg> Movement;
    public readonly int Duration;
    public readonly int HitMaxCount;
    public readonly int HitGapTime;
    public readonly int CustemToughPower;
    public readonly MediaType MediaType;
    public readonly System.Collections.Generic.List<string> MediaExtraParameters;
    public readonly TargetTypeTag TargetType;
    public readonly System.Collections.Generic.List<string> EffectAlias;
   
    public const int __ID__ = 785396342;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Movement) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "alias:" + Alias + ","
        + "viewResPath:" + ViewResPath + ","
        + "colliderShapeType:" + ColliderShapeType + ","
        + "colliderParam:" + Luban.StringUtil.CollectionToString(ColliderParam) + ","
        + "Movement:" + Luban.StringUtil.CollectionToString(Movement) + ","
        + "duration:" + Duration + ","
        + "hitMaxCount:" + HitMaxCount + ","
        + "hitGapTime:" + HitGapTime + ","
        + "custemToughPower:" + CustemToughPower + ","
        + "mediaType:" + MediaType + ","
        + "mediaExtraParameters:" + Luban.StringUtil.CollectionToString(MediaExtraParameters) + ","
        + "targetType:" + TargetType + ","
        + "effectAlias:" + Luban.StringUtil.CollectionToString(EffectAlias) + ","
        + "}";
    }
}

}

