
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class SkillEffectCfg : Luban.BeanBase
{
    public SkillEffectCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Alias = _buf.ReadString();
        Desc = _buf.ReadString();
        EffectType = (EffectType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Parameters = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Parameters.Add(_e0);}}
    }

    public static SkillEffectCfg DeserializeSkillEffectCfg(ByteBuf _buf)
    {
        return new battle.SkillEffectCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 别名
    /// </summary>
    public readonly string Alias;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly EffectType EffectType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> Parameters;
   
    public const int __ID__ = 414844376;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "alias:" + Alias + ","
        + "desc:" + Desc + ","
        + "effectType:" + EffectType + ","
        + "Parameters:" + Luban.StringUtil.CollectionToString(Parameters) + ","
        + "}";
    }
}

}

