
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class SkillActCfg : Luban.BeanBase
{
    public SkillActCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Alias = _buf.ReadString();
        SpCost = _buf.ReadInt();
        ParryWindow = _buf.ReadInt();
        DodgeWindow = _buf.ReadInt();
        BaseTough = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SelfEffectAlias = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SelfEffectAlias.Add(_e0);}}
        LockMediaAlias = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);LaunchTimeToMediaAlias = new System.Collections.Generic.List<LauncherCfg>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { LauncherCfg _e0;  _e0 = global::cfg.LauncherCfg.DeserializeLauncherCfg(_buf); LaunchTimeToMediaAlias.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MoveChangeTimeS = new System.Collections.Generic.List<MovementChangeCfg>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MovementChangeCfg _e0;  _e0 = global::cfg.MovementChangeCfg.DeserializeMovementChangeCfg(_buf); MoveChangeTimeS.Add(_e0);}}
        KeepDistance = _buf.ReadInt();
        SkillAIRange = _buf.ReadInt();
        SkillMustTime = _buf.ReadInt();
        ComboInputCacheStartTime = _buf.ReadInt();
        SkillMaxTime = _buf.ReadInt();
    }

    public static SkillActCfg DeserializeSkillActCfg(ByteBuf _buf)
    {
        return new battle.SkillActCfg(_buf);
    }

    public readonly int Id;
    public readonly string Alias;
    public readonly int SpCost;
    public readonly int ParryWindow;
    public readonly int DodgeWindow;
    public readonly int BaseTough;
    public readonly System.Collections.Generic.List<string> SelfEffectAlias;
    public readonly string LockMediaAlias;
    public readonly System.Collections.Generic.List<LauncherCfg> LaunchTimeToMediaAlias;
    public readonly System.Collections.Generic.List<MovementChangeCfg> MoveChangeTimeS;
    public readonly int KeepDistance;
    public readonly int SkillAIRange;
    public readonly int SkillMustTime;
    public readonly int ComboInputCacheStartTime;
    public readonly int SkillMaxTime;
   
    public const int __ID__ = 1283866573;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LaunchTimeToMediaAlias) { _e?.ResolveRef(tables); }
        foreach (var _e in MoveChangeTimeS) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "alias:" + Alias + ","
        + "spCost:" + SpCost + ","
        + "parryWindow:" + ParryWindow + ","
        + "dodgeWindow:" + DodgeWindow + ","
        + "baseTough:" + BaseTough + ","
        + "SelfEffectAlias:" + Luban.StringUtil.CollectionToString(SelfEffectAlias) + ","
        + "lockMediaAlias:" + LockMediaAlias + ","
        + "launchTimeToMediaAlias:" + Luban.StringUtil.CollectionToString(LaunchTimeToMediaAlias) + ","
        + "moveChangeTimeS:" + Luban.StringUtil.CollectionToString(MoveChangeTimeS) + ","
        + "keepDistance:" + KeepDistance + ","
        + "skillAIRange:" + SkillAIRange + ","
        + "skillMustTime:" + SkillMustTime + ","
        + "comboInputCacheStartTime:" + ComboInputCacheStartTime + ","
        + "skillMaxTime:" + SkillMaxTime + ","
        + "}";
    }
}

}

