
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public partial class TbBodyCfg
{
    private readonly System.Collections.Generic.List<battle.BodyCfg> _dataList;

    private System.Collections.Generic.Dictionary<int, battle.BodyCfg> _dataMap_id;
    private System.Collections.Generic.Dictionary<string, battle.BodyCfg> _dataMap_alias;

    public TbBodyCfg(ByteBuf _buf)
    {
        _dataList = new System.Collections.Generic.List<battle.BodyCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.BodyCfg _v;
            _v = global::cfg.battle.BodyCfg.DeserializeBodyCfg(_buf);
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, battle.BodyCfg>();
        _dataMap_alias = new System.Collections.Generic.Dictionary<string, battle.BodyCfg>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
    }

    public System.Collections.Generic.List<battle.BodyCfg> DataList => _dataList;

    public battle.BodyCfg GetById(int key) => _dataMap_id.TryGetValue(key, out battle.BodyCfg __v) ? __v : null;
    public battle.BodyCfg GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out battle.BodyCfg __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

