
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public partial class TbCommonCfg
{

     private readonly battle.CommonCfg _data;

     public battle.CommonCfg Data => _data;

    public TbCommonCfg(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.battle.CommonCfg.DeserializeCommonCfg(_buf);
    }


    /// <summary>
    /// 每个tick的时间
    /// </summary>
     public int TickTime => _data.TickTime;
     public int TickToughGrow => _data.TickToughGrow;
    /// <summary>
    /// 最小动作判定时间0,小于等于此值的动作不在博弈空间内
    /// </summary>
     public int MinActTime => _data.MinActTime;
    /// <summary>
    /// 最大动作判定时间20
    /// </summary>
     public int MaxActTime => _data.MaxActTime;
    /// <summary>
    /// 均值
    /// </summary>
     public int AvgActTime => _data.AvgActTime;
    /// <summary>
    /// 摩擦加速度值 mm*s^-2
    /// </summary>
     public int Friction => _data.Friction;
    /// <summary>
    /// 判定平局触发的效果
    /// </summary>
     public string DrawStunAlias => _data.DrawStunAlias;
    /// <summary>
    /// 低于minTough对于非Stun目标直接判负
    /// </summary>
     public int MinTough => _data.MinTough;
    /// <summary>
    /// 高于或等于maxTough对于目标判胜
    /// </summary>
     public int MaxTough => _data.MaxTough;
    /// <summary>
    /// 中间值，大于等于此值，非攻击状态可以接住此攻击
    /// </summary>
     public int MidTough => _data.MidTough;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

